print(2>1)
print(2<1)
print(2==1)
print(2!=1)
print(2>=1)
print(2<=1)
print("______________________________")
print(True or True)
print(True or False)
print(False or True)
print(False or False)