nested_dictionary={
    "one":
        {
            "name":"john",
            "age":30,
            "city":"new york"
        },
    "two":
        {
            "name":"jane",
            "age":25,
            "city":"paris"
        },
    "three":
        {
            "name":"boby",
            "age":20,
            "city":"london"
 }
}
print(nested_dictionary)
print(nested_dictionary["three"]["name"])